/*
 * generated by Xtext 2.24.0
 */
package xtext.magicSHACL.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SimpleUiModule extends AbstractSimpleUiModule {

	public SimpleUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
