/*
 * generated by Xtext 2.24.0
 */
package xtext.magicSHACL;

import org.eclipse.emf.ecore.EPackage;

import com.google.inject.Injector;

import magicSHACL.MagicSHACLPackage;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SimpleStandaloneSetup extends SimpleStandaloneSetupGenerated {

	public static void doSetup() {
		new SimpleStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
	
	@Override
	public void register(Injector injector) {
		EPackage.Registry.INSTANCE.put(MagicSHACLPackage.eNS_URI, MagicSHACLPackage.eINSTANCE);
		super.register(injector);
	}
}
