/*
 * generated by Xtext 2.24.0
 */
package xtext.magicSHACL;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TurtleStandaloneSetup extends TurtleStandaloneSetupGenerated {

	public static void doSetup() {
		new TurtleStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
