/*
 * generated by Xtext 2.24.0
 */
package xtext.magicSHACL.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTurtleScopeProvider extends DelegatingScopeProvider {
}
