/*
 * generated by Xtext 2.24.0
 */
package xtext.magicSHACL.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import xtext.magicSHACL.parser.antlr.internal.InternalTurtleParser;
import xtext.magicSHACL.services.TurtleGrammarAccess;

public class TurtleParser extends AbstractAntlrParser {

	@Inject
	private TurtleGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTurtleParser createParser(XtextTokenStream stream) {
		return new InternalTurtleParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Graph";
	}

	public TurtleGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TurtleGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
