/*
 * generated by Xtext 2.24.0
 */
package xtext.magicSHACL.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import xtext.magicSHACL.ui.internal.MagicSHACLActivator;

public class SimpleUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MagicSHACLActivator.getInstance().getInjector("xtext.magicSHACL.Simple");
	}

}
